# Generated by Django 2.1.2 on 2018-10-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('file', models.URLField(verbose_name='Archivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artefacto',
                'verbose_name_plural': 'Artefactos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del recurso', max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('Web page', 'Web page'), ('Banner', 'Banner')], help_text='Tipo del recurso ()', max_length=50, verbose_name='Tipo')),
                ('priority', models.IntegerField(choices=[(3, 'Baja'), (2, 'Media'), (1, 'Baja')], verbose_name='Prioridad')),
                ('estimated_duration', models.FloatField(verbose_name='Duración estimada')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('current_phase', models.IntegerField(choices=[(1, 'Preproducción'), (2, 'Producción'), (3, 'Postproducción'), (4, 'Control de calidad')], default=1, verbose_name='Fase actual')),
                ('artifacts', models.ManyToManyField(related_name='artifact_resources', to='resources.Artifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_resources', to='resources.Project')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='WorkplanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('duration', models.IntegerField(verbose_name='Duración')),
                ('periodicity', models.IntegerField(choices=[(1, 'Cada hora'), (2, 'Diario'), (3, 'Semanal'), (4, 'Quincenal'), (5, 'Mensual')], verbose_name='Periodicidad')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplan_activities', to='resources.Resource')),
            ],
            options={
                'verbose_name': 'Actividad del plan de trabajo',
                'verbose_name_plural': 'Actividades del plan de trabajo',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resource',
            name='users',
            field=models.ManyToManyField(related_name='user_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
