# Generated by Django 2.1.2 on 2018-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanactivity',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='workplanactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Iniciado'), (2, 'No iniciado'), (3, 'Finalizado')], default=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='estimated_duration',
            field=models.FloatField(verbose_name='Duración estimada en días'),
        ),
        migrations.AlterField(
            model_name='workplanactivity',
            name='periodicity',
            field=models.IntegerField(choices=[(1, 'Cada hora'), (2, 'Diario'), (3, 'Semanal'), (4, 'Quincenal'), (5, 'Mensual'), (6, 'N/A')], verbose_name='Periodicidad'),
        ),
    ]
