# Generated by Django 2.1.2 on 2018-10-12 01:52

from django.conf import settings
from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanactivity',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='workplanactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Iniciado'), (2, 'No iniciado'), (3, 'Finalizado')], default=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='workplanactivity',
            name='users',
            field=models.ManyToManyField(related_name='users_workplan_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='estimated_duration',
            field=models.FloatField(verbose_name='Duración estimada en días'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Baja'), (2, 'Media'), (1, 'Alta')], verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='workplanactivity',
            name='periodicity',
            field=models.IntegerField(choices=[(1, 'Cada hora'), (2, 'Diario'), (3, 'Semanal'), (4, 'Quincenal'), (5, 'Mensual'), (6, 'N/A')], verbose_name='Periodicidad'),
        ),
    ]
