# Generated by Django 2.1 on 2018-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='agilesreds')),
            ],
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.URLField(verbose_name='Archivo'),
        ),
    ]
