# Generated by Django 2.1 on 2018-10-06 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_auto_20180928_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanactivity',
            name='users',
            field=models.ManyToManyField(related_name='users_workplan_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.URLField(verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Baja'), (2, 'Media'), (1, 'Alta')], verbose_name='Prioridad'),
        ),
    ]
