# Generated by Django 2.1.1 on 2018-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180929_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
