# Generated by Django 2.1.2 on 2018-11-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20181009_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='resources.Resource')),
            ],
            options={
                'verbose_name': 'MeetingRecord',
                'verbose_name_plural': 'MeetingRecords',
            },
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.TextField(verbose_name='File'),
        ),
    ]
