# Generated by Django 2.1.1 on 2018-10-06 13:50

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20180930_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
