# Generated by Django 2.1.2 on 2018-11-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resourcecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecomment',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
    ]
