# Generated by Django 2.1.1 on 2018-10-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20181006_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='file',
            new_name='custom_filename',
        ),
    ]
