# Generated by Django 2.1 on 2018-11-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20181111_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='users',
        ),
    ]
