# Generated by Django 2.1 on 2018-11-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0008_remove_resource_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Preproducción'), (2, 'Producción'), (3, 'Postproducción'), (4, 'Control de calidad')], default=1, verbose_name='Fase del recurso')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='resources.Resource')),
                ('users', models.ManyToManyField(related_name='phase_resources_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
    ]
